name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f tracing_bug_bash/requirements.txt ]; then pip install -r tracing_bug_bash/requirements.txt; fi
          pip install pytest==8.*
          
      - name: Run tests
        run: |
          pytest -q 